[package]
name = "script"
description = "Generate image previews for the simply_colored crate"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.29"
image = "0.25.6"
imageproc = "0.25.0"
strum = { version = "0.27.1", features = ["derive"] }
